framework:
    default_locale: '%locale%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: '%locale%'
        enabled_locales: ['en', 'pt', 'pt_pt', 'pt_br', 'es']
