controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

app_main:
    resource: ../../src/Controller
    type: annotation
    prefix:
        en: '/en'
        pt: '/pt'
        es: '/es'
        #pt_pt: '/pt_pt'
        #pt_br: '/pt_br'
